run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - gosec
    - gocritic

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - unused
